#!/usr/bin/env bash
# Install scout for use by an agent:
#   1. a `scout` launcher on PATH (runs this repo's scout.py via uv, from anywhere)
#   2. the scout skill, so an agent knows how to use it
#
# The skill is COPIED by default (self-contained, frozen). Pass --symlink to link
# it to this repo instead, so edits here show up live.
#
#   ./install.sh              # copy the skill
#   ./install.sh --symlink    # symlink the skill (dev)
#
# Override locations with SCOUT_BINDIR and SCOUT_SKILLDIR.
set -euo pipefail

REPO="$(cd "$(dirname "$0")" && pwd)"
BINDIR="${SCOUT_BINDIR:-$HOME/.local/bin}"
SKILLDIR="${SCOUT_SKILLDIR:-$HOME/.claude/skills}"
MODE=copy
for arg in "$@"; do
  case "$arg" in
    --symlink) MODE=symlink ;;
    -h|--help) sed -n '2,12p' "$0"; exit 0 ;;
    *) echo "unknown argument: $arg" >&2; exit 2 ;;
  esac
done

# 1. launcher
mkdir -p "$BINDIR"
cat > "$BINDIR/scout" <<EOF
#!/usr/bin/env bash
# Auto-generated by scout/install.sh — runs scout from $REPO, cwd-independent.
exec uv run --project "$REPO" python "$REPO/scout.py" "\$@"
EOF
chmod +x "$BINDIR/scout"
echo "launcher: $BINDIR/scout"
case ":$PATH:" in
  *":$BINDIR:"*) ;;
  *) echo "  ⚠ $BINDIR is not on your PATH — add it, or run scout by full path" ;;
esac

# 2. skill
mkdir -p "$SKILLDIR"
rm -rf "$SKILLDIR/scout"
if [ "$MODE" = symlink ]; then
  ln -s "$REPO/.claude/skills/scout" "$SKILLDIR/scout"
  echo "skill:    $SKILLDIR/scout -> $REPO/.claude/skills/scout (symlink)"
else
  cp -R "$REPO/.claude/skills/scout" "$SKILLDIR/scout"
  echo "skill:    $SKILLDIR/scout (copy)"
fi

echo "done. try:  scout --survey \"what does this repo do?\" --repo ."
